name: Sync Spring Docs

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Sync Spring Docs
    runs-on: ubuntu-latest
    env:
      ARTIFACTORY_USERNAME: ${{ secrets.COMMERCIAL_ANNOTATE_ARTIFACTORY_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.COMMERCIAL_ANNOTATE_ARTIFACTORY_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Download Spring Docs from Artifactory
        run: ./download-spring-docs/src/action.sh --artifactory-username "$ARTIFACTORY_USERNAME" --artifactory-password "$ARTIFACTORY_PASSWORD" --docs-base-dir docs
      - name: Inject OneTrust
        run: ./inject-onetrust/src/action.sh --docs-base-dir docs
      - name: 'auth'
        uses: 'google-github-actions/auth@v2.1.0'
        with:
          credentials_json: '${{ secrets.COMMERCIAL_DOCS_GCP_BUCKET_JSON }}'
      - id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v2.1.0'
        with:
          path: 'docs'
          destination: 'commercial-docs.spring.io'
          parent: false
