name: Sync Spring Docs

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Sync Spring Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Spring Docs from Artifactory
        run: echo 'TBD'
      - name: Inject OneTrust
        run: echo 'TBD'
